name = "SP_IRK"
uuid = "1f30a8fe-09c3-4f49-997a-28583bc83015"
authors = ["Fabio Durastante <fabio.durastante@unipi.it>", "Mariarosa Mazza <mariarosa.mazza@uniroma2.it>"]
version = "1.0.0-DEV"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RungeKutta = "fb486d5c-30a0-4a8a-8415-a8b4ace5a6f7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
FastGaussQuadrature = "1.0.2"
LinearAlgebra = "1.11.0"
MatrixEquations = "2.4.5"
QuadGK = "2.11.2"
RungeKutta = "0.5.15"
SparseArrays = "1.11.0"
julia = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
